services:
  quarkus-db:
    image: postgres:15.1
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=quarkus
      - POSTGRES_PASSWORD=quarkus
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U quarkus" ]
      interval: 5s
      timeout: 5s
      retries: 6
    ports:
      - "5432:5432"
    networks:
      - quarkus

  ollama:
    image: ollama/ollama:0.5.13
    container_name: ollama
    restart: unless-stopped
    pull_policy: always
    tty: true
    volumes:
      - ~/root/.ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - 11434:11434
    networks:
      - quarkus
    entrypoint: [ "/usr/bin/bash", "/entrypoint.sh" ]
    env_file: "./backend/.env"

networks:
  quarkus:
    driver: bridge

volumes:
  db-data:
    driver: local
