:toc: macro
toc::[]

== Setup

Install https://github.com/devonfw/IDEasy[IDEasy]:

* Install https://git-scm.com/downloads[git] if not already installed (download and run installer or run `winget install Git.Git` in PowerShell or CMD)
* *If you use Windows, please download Windows MSI for IDEasy installation.*
+
Download and install IDEasy from https://github.com/devonfw/IDEasy/releases[here]. The Windows MSI file is not yet signed so you have to select `More info` (see bug https://github.com/devonfw/IDEasy/issues/1102[#1102]).
* Open git-bash and run the following command:
+
```
ide create java-quarkus https://github.com/devonfw-training/java-quarkus-settings.git
```
* Wait until the setup process has completed.
* If you do not have already Docker Desktop or Rancher Desktop installed, you should do so by running in Git-Bash the command:
+
```
ide install docker
```

=== Build Backend

Now we build our application `backend`:

* Go to folder `workspaces/main/java-quarkus/` in `java-quarkus`.
* In Windows-Explorer right-click it and select `Git Bash Here`.
* In the git-bash at this folder run the following command:
+
[source,commandline]
----
mvn clean install -DskipTests
----

==== Import into an IDE

Please choose your favorite IDE.
For best support from the trainers we recommend to use IntelliJ.

===== IntelliJ

* Launch IntelliJ via `ide intellij`
* In your Intellij `Project` view open `java-quarkus` folder and select `pom.xml`.
* Right-click on it and select `+ Add as maven project`

===== Eclipse

Next, we import the new `backend` project into our Eclipse IDE:

* `ide eclipse`
* In Eclipse `Import` as `Existing Maven Project`, there click `Browse` and choose your `backend` folder in `workspaces/main/java-quarkus`.
* Now find the green bug icon in the Eclipse toolbar and click on the down-arrow right to it.
* Click `Debug Configuration` from the menu
* In the appearing `Debug Configuration` popup window select `Quarkus application` from the list on the left.
* Click on the first icon from the bar above that list (with tooltip `New launch configuration`)
* Change the `Name` to `app` and ensure the `Project` is set to `app`.
* Click on `Debug` to start your app in debug mode.
* Open http://localhost:8080/ in your browser and you should see the quarkus welcome page of the app.

=== Build Frontend
The frontend is written in react and can be build with yarn. Please go into `frontend` and run `yarn install` on a command line. Please do not use npm.

When the build was successful and the backend is running, too, you can start the frontend by running `yarn start` in the same directory.

The frontend is reachable under http://localhost:3000/. You can append the id of the list you want to load, default is 1: http://localhost:3000/1.

=== Links
* https://github.com/devonfw/IDEasy[IDEasy]
